import re
import unicodedata

def clean_text(raw_text: str)->str:
    """Main text cleaning pipeline for OCR/PDF extracted text."""
    text=raw_text
    text=unicodedata.normalize("NFKC", text) #normalize unicode (smart quotes, dashes etc)
    replacements={
        "“": '"', "”": '"', "‘": "'", "’": "'",
        "–": "-", "—": "-", "−": "-", "•": "-",
        "₹.": "₹", "Rs.": "₹", "Rs": "₹", "INR": "₹"
    }
    for old, new in replacements.items():
        text=text.replace(old, new)

    text=re.sub(r"[\x00-\x1F\x7F]", "", text) #remove invisible/control characters and BOMs
    text=text.replace("\u00A0", " ")

    text=re.sub(r"\s+", " ", text).strip() #normalize whitespace

    #fix common OCR misreads (context-aware)
    #0<->O confusion
    text=re.sub(r"(?<=\b)[0O](?=[A-Za-z])", "O", text)
    #1<->l confusion
    text=re.sub(r"(?<=[A-Za-z])[1I](?=[a-z])", "l", text)
    #5<->S confusion
    text=re.sub(r"(?<=\b)5(?=[A-Za-z])", "S", text)

    #normalize currency & numbers
    text=re.sub(r"\b(Rs|RS|INR)\.?\b", "₹", text, flags=re.IGNORECASE)
    text=re.sub(r"₹\s+", "₹", text)
    text=re.sub(r"(\d)\s+%", r"\1%", text) #10 % -> 10%

    #remove stray spaces inside numbers
    text=re.sub(r"(\d)\s+(\d{2,3})", r"\1\2", text)

    #fix ordinals & punctuation
    text=re.sub(r"(\d+)[!¡]", r"\1th", text)

    #remove page artifacts/boilerplate
    patterns_to_remove=[
        r"Page\s*\d+(\s*of\s*\d+)?",
        r"Export to Sheets",
        r"Generated by .*",
    ]
    for pat in patterns_to_remove:
        text=re.sub(pat, "", text, flags=re.IGNORECASE)

    #normalize dates (basic standardization)
    text=re.sub(
        r"(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})",
        lambda m: f"{m.group(3).zfill(4)}-{m.group(2).zfill(2)}-{m.group(1).zfill(2)}",
        text,
    )

    #final collapse of spaces
    text=re.sub(r"\s+", " ", text).strip()
    return text

def parse_number(value: str):
    """Convert numeric strings to int/float safely or return None."""
    s=re.sub(r"[^\d.\-]", "", value)
    try:
        return int(float(s)) if "." not in s else float(s)
    except ValueError:
        return None

def remove_headers_and_footers(text_lines: list[str]) -> list[str]:
    """Detect and remove repeated headers/footers across pages."""
    from collections import Counter
    counter=Counter(text_lines)
    headers={line for line, count in counter.items() if count>1 and len(line)<60}
    return [line for line in text_lines if line.strip() not in headers]